name = "cloudflare-docker-proxy"
main = 'src/index.js'
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.production]
name = "cloudflare-docker-proxy"

routes = [
  { pattern = "hub.your.domain", custom_domain = true },
  # { pattern = "quay.your.domain", custom_domain = true },
  # { pattern = "gcr.your.domain", custom_domain = true },
  # { pattern = "k8s-gcr.your.domain", custom_domain = true },
  # { pattern = "k8s.your.domain", custom_domain = true },
  # { pattern = "ghcr.your.domain", custom_domain = true },
  # { pattern = "cloudsmith.your.domain", custom_domain = true },
  # { pattern = "ecr.your.domain", custom_domain = true },
]

[env.production.vars]
MODE = "production"
DEFAULT_DOCKER_REGISTRY_URL = "https://index.docker.io"
DEFAULT_DOCKER_REGISTRY_AUTH_URL = "https://auth.docker.io/token"
GET_TOKEN_BY_CF = false

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.your.domain", custom_domain = true }

[env.staging.vars]
MODE = "staging"
DEFAULT_DOCKER_REGISTRY_URL = "https://index.docker.io"
DEFAULT_DOCKER_REGISTRY_AUTH_URL = "https://auth.docker.io/token"
GET_TOKEN_BY_CF = false
