name = "cloudflare-docker-proxy"
main = 'src/index.js'
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.production]
name = "cloudflare-docker-proxy"

routes = [
  { pattern = "hub.docker.proxy.meng.hu", custom_domain = true },
  # { pattern = "quay.docker.proxy.meng.hu", custom_domain = true },
  # { pattern = "gcr.docker.proxy.meng.hu", custom_domain = true },
  # { pattern = "k8s-gcr.docker.proxy.meng.hu", custom_domain = true },
  # { pattern = "k8s.docker.proxy.meng.hu", custom_domain = true },
  # { pattern = "ghcr.docker.proxy.meng.hu", custom_domain = true },
  # { pattern = "cloudsmith.docker.proxy.meng.hu", custom_domain = true },
  # { pattern = "ecr.docker.proxy.meng.hu", custom_domain = true },
]

[env.production.vars]
MODE = "production"
DEFAULT_DOCKER_REGISTRY_URL = "https://index.docker.io"
DEFAULT_DOCKER_REGISTRY_AUTH_URL = "https://auth.docker.io/token"
FORWARD_TOKEN = true

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.docker.proxy.meng.hu", custom_domain = true }

[env.staging.vars]
MODE = "staging"
DEFAULT_DOCKER_REGISTRY_URL = "https://index.docker.io"
DEFAULT_DOCKER_REGISTRY_AUTH_URL = "https://auth.docker.io/token"
FORWARD_TOKEN = false
